### ISSUE TITLE
JOSS review: fix paper building

### ISSUE THREAD

**Issue by dirmeier** [BIPL-HORIE/LIBSDNN#1]
Hi,
before we can start with the review please make sure the PDF builds properly. This is probably an ORCID formatting error or so.
Best,
Simon

**Comment by BIPL-HORIE** [comment]
Thank you for contacting me.
Perhaps, it caused by the lack of ORCID of some authors.
Now, I'm asking them to sign up ORCID.
I will fix it soon.

Thank you.

**Comment by BIPL-HORIE** [comment]
We added the ORCID.
We kindly ask for your confirmation.

Thank you.

**Comment by dirmeier** [comment]
The paper still looks to be broken. Could you check here pls: https://github.com/openjournals/joss-reviews/issues/1785
